version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Environment name setting
          command: if [ $CIRCLE_BRANCH='master' ]; then export ENV=prd;  else export ENV=$CIRCLE_BRANCH; fi
      - run:
          name: Debug
          command: echo $ENV
      - run:
          name: Validate
          command: packer validate template.json
      - run:
          name: Build
          command: packer build template.json
